### ISSUE TITLE
Peer review for midterm recall 2

### ISSUE THREAD

**Issue by IsmailTadji** [aliskyalisky/Musilink#1]
Hi,

The project looks good overall, especially the effort in CSS instead of using bootstrap!

However there are a few points that can improve the project.

Firstly repository includes your personal venv, which should be ignored in .gitignore. I also had issues installing the application, but overcame it by using "pip3" instead of using "pip" for installing dependancies. Every method you have applied works appropriately, but the registration lacks username character limit, which breaks the UI in conversations.

All in all, a really good project so far, and I'm sure it will be great!

**Comment by aliskyalisky** [comment]
Thank you for the good pointers, will work on these!
