### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by annis1234** [aliskyalisky/Musilink#2]
- Sovelluksella on selkeä idea ja käyttötarkoitus, joka kuulostaa hyödylliseltä käytännön elämässä. Sovelluksen ulkoasu on hieno ja näyttää jo ammattimaiselta. Navigointi on helppoa ja sujuvaa. Sovelluksen asentaminen onnistui helposti dokumentaation ohjeiden mukaan, ja dokumentaatio vaikuttaa muutenkin olevan ajan tasalla. Koodi on siistiä ja hyvin refaktoroitu.
- Julkisessa repositoriossa on muutama ylimääräinen hakemisto (__pycache__, .DS_store ja venv). Ne voisi poistaa, ohjeita mm. täällä https://stackoverflow.com/questions/1143796/remove-a-file-from-a-git-repository-without-deleting-it-from-the-local-filesyste
- Syötteet kaipaisivat vielä validointia ja virheidenkäsittelyä voisi parantaa.  Keskustelun avaaminen ja viestin lähettäminen onnistuu, vaikka tekstikenttä olisi tyhjä. Sovellus kaatuu, jos käyttäjä yrittää luoda tunnuksen jo olemassaolevalla käyttäjänimellä. Kirjautumisen epäonnistumisesta tulee asiallinen virheviesti.

**Comment by aliskyalisky** [comment]
Kiitos vinkeistä! Ylimääräiset hakemistot on nyt poistettu reposta ja syötteiden validointia ja virheidenkäsittelyä parannettu. Mainitsemiasi ongelmia ei pitäisi enää olla.
